### ISSUE TITLE
how sinopia support 'npm ping' ?

### ISSUE THREAD

**Issue by burtbai** [rlidwka/sinopia#486] opened 2018-08-16 15:05 UTC

**Comment by burtbai** [comment] 2018-08-16 15:26
now，nginx add 
```
location /-/ping { 
    return 200 '{}'; 
}
```
work

**Comment by romain-neil** [comment] 2019-02-23 19:55
If the issue is solved, could you close it  for better stats ? Thanks

**Closed as completed** 2019-02-27 05:14 UTC
